### PR TITLE
Add blocking of fixup/squash commits

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by TheNeikos** [comment]
Can you please send a fixup or squash commit?

**Comment by matthiasbeyer** [comment]
I guess I have to make bors also depend on the job, right? :laughing:

**Comment by TheNeikos** [comment]
I am mostly confused on why the PR checks are not show up?

**Comment by matthiasbeyer** [comment]
Same

**Comment by matthiasbeyer** [comment]
I guess the problem was because the pr linting checks do not run on the "push" target (the fixup-block one actually fails on that target, because the authors of the check want it only to be possible on `pull_request`).

Because of that, bors cannot query the checks and thus fails to do anything I guess.

I've changed the setup here so that the commit linting happens in a separate workflow file.

**Comment by TheNeikos** [comment]
This seems to be working fine: 

https://github.com/TheNeikos/cloudmqtt/blob/6f84144197d85b3941ef3730d36cdf70306aff7c/.github/workflows/check.yml#L32-L35

Could you add it back to the main workflow? I'd rather have it in one file.

**Comment by matthiasbeyer** [comment]
Like this?

**Comment by TheNeikos** [comment]
Yeah! It’s working!

**Comment by TheNeikos** [comment]
bors merge

**Pull request merged**
