### PR TITLE
Clippy deny methods/types

### PR DESCRIPTION
**Pull request by matthiasbeyer**
These patches makes clippy deny certain methods and types in the `mqtt-format` crate.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Seems to work as planed.

**Comment by TheNeikos** [comment]
I like it!

**Comment by matthiasbeyer** [comment]
Okay! I would go then and fix the remaining issues. That would mean that I have to make the `MSubscriptionIter` and `MUnsubscriptionIter` failable. Sounds good?

**Comment by TheNeikos** [comment]
No, they shouldn't be failable. Instead I'd rather they be matched and the error branch be `unreachable!`, since it logically is.

**Comment by matthiasbeyer** [comment]
Like this? :laughing:

**Comment by TheNeikos** [comment]
yup!

**Comment by matthiasbeyer** [comment]
IMO ready for merge...

**Comment by TheNeikos** [comment]
bors merge

**Pull request merged**
