### PR TITLE
Output type enhancements

### PR DESCRIPTION
**Pull request by matthiasbeyer**
These patches are extracted from #123 to make that PR less complex and rebasing easier.

### CODE REVIEW

**Comment by TheNeikos** [comment]
Looks good but there are conflicts!

**Comment by matthiasbeyer** [comment]
Rebased.

**Comment by matthiasbeyer** [comment]
bors cancel

bors retry

**Comment by matthiasbeyer** [comment]
bors ping

**Comment by matthiasbeyer** [comment]
bors merge

**Pull request merged**
